---
title: "P8110 Homework Two"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(knitr)
```

\begin{center}
\textbf{Nick Williams \\
ntw2117}
\end{center}

## Problem 1

(a) $$\hat{t_{0.5}} = \text{min}\{t_j: \hat{S}(t_j) < 0.5\}$$

1: identify $\hat{t_j}$ such that $\hat{S}(t_j) < 0.5$

```{r echo = FALSE}
med <- tibble("$\\hat{t_j}$" = c("$t_6$", "$t_5$", "$t_4$"), 
              "$\\hat{S}(t_j)$" = c(0.0, 0.2667, 0.4))

kable(med, escape = FALSE)
```
  
2: identify minimum $\hat{t_j}:\hat{t_4} = 5$  

$$
\begin{aligned}
95 \% \text{CI} &= \text{all } t_j \text{CI} \ni 0.5\\
&= t_1, t_2, t_3, t_4, t_5 \\
&= [0.4, 1.2), [1.2, 4.3), [4.3, 5.0), [5.0, 5.1), [5.1, 7.1) \\
&= [0.4, 7.1)
\end{aligned}
$$
 
We estimate that 50% of patients will survive for more than 5 years. Furthermore, we are 95% confident that the true median survival time is between 0.4 and 7.1 years. 

(b)  
$$
\begin{aligned}
\hat{\mu}_{t_j} &= \sum_{j = 1}^J \hat{S}(t_{j - 1})(t_j - t_{j-1}) \\
&= 1(0.4) + 0.9(1.2 - 0.4) + 0.8(4.3 - 1.2) + 0.6667(5.0 - 4.3) + 0.4(5.1 - 5.0) + 0.2667(7.1 - 5.1) \\
&= 0.4 + 0.72 + 2.48 + 0.4667 + 0.04 + 0.5334 \\
&= 4.64
\end{aligned}
$$

The estimated average suvival time is 4.64 years. 
